import { createApp } from 'vue'
import App from './App.vue'
import router from './router'

import '@/assets/bootstrap.min.css'
import '@/assets/bootstrap.bundle.min.js'
import '@/assets/dopstyle.css'

import '@/assets/css/style.css'

// import 'https://code.jquery.com/jquery-3.6.0.min.js'
// import '@/assets/js/jquery-3.2.1.min.js'
// import '@/assets/js/jquery-migrate-3.0.1.min.js'
// import '@/assets/js/jquery.animateNumber.min.js'
// import '@/assets/js/jquery.easing.1.3.js'
// import '@/assets/js/jquery.magnific-popup.min.js'
// import '@/assets/js/jquery.min.js'
// import '@/assets/js/jquery.stellar.min.js'
// import '@/assets/js/jquery.waypoints.min.js'
// import '@/assets/js/main.js'
import '@/assets/css/bootstrap/bootstrap-grid.css'
import '@/assets/css/bootstrap/bootstrap-reboot.css'
import '@/assets/css/ajax-loader.gif'
import '@/assets/css/animate.css'
import '@/assets/css/bootstrap-datepicker.css'
// import '@/assets/css/bootstrap.min.css'
// import '@/assets/css/flaticon.css'
// import '@/assets/css/icomoon.css'
// import '@/assets/css/ionicons.min.css'
import '@/assets/css/magnific-popup.css'
// import '@/assets/css/owl.carousel.min.css'
import '@/assets/css/owl.theme.default.min.css'
import '@/assets/css/css/bootstrap-reboot.css'
import '@/assets/css/css/mixins/_text-hide.css'
// import '@/assets/js/bootstrap.min.js'
// import '@/assets/js/google-map.js'
// import '@/assets/js/owl.carousel.min.js'
import '@/assets/js/popper.min.js'
import '@/assets/js/scrollax.min.js'


createApp(App).use(router).mount('#app')